// vue-cancelToken/src/views/MessageManage.vue
<template>
  <div>
    <el-table border :data="data" v-loading="loading">
      <el-table-column
        v-for="c in columns"
        :key="c.prop"
        :prop="c.prop"
        :label="c.label"
        :align="c.align"
        :formatter="c.formatter"
      ></el-table-column>
    </el-table>
    <el-pagination
      class="data-pagination"
      layout="prev, pager, next"
      :total="allData.length"
      :page-Size="10"
      :current-page="pageId"
      @current-change="changePage"
    ></el-pagination>
  </div>
</template>

<script>
import cancelTokenMixin from '../mixin/cancelTokenMixin'

export default {
  name: 'MessageManage',
  mixins: [cancelTokenMixin],
  data () {
    return {
      pageName: '信息管理页面',
      allData: [],
      data: [],
      loading: false,
      pageId: 1,
      pageSize: 10,
      columns: [
        {
          prop: 'index',
          label: '索引',
          align: 'center'
        },
        {
          prop: 'name',
          label: '名称',
          align: 'center'
        },
        {
          prop: 'age',
          label: '年龄',
          align: 'center'
        },
        {
          prop: 'money',
          label: '财产',
          align: 'center',
          formatter: row => `${row.money}元`
        }
      ]
    }
  },
  mounted () {
    this.getData()
  },
  methods: {
    getData () {
      this.loading = true
      axios.get('http://localhost:7000/message', { cancelToken: this.cancelToken }).then(res => {
        const data = res.data
        if (data.success) {
          this.allData = data.message
          this.changePage()
        }
      }).catch(err => {
        const message = err.message || '获取数据失败';
        console.log(message);
         this.$message({
          type: 'error',
          message
        })
      }).finally(() => {
        this.loading = false
      })
    },
    changePage (page) {
      if (page) {
        this.data = this.allData.slice((page - 1) * this.pageSize, page * this.pageSize)
        return
      }
      this.data = this.allData.slice((this.pageId - 1) * this.pageSize, this.pageId * this.pageSize)
    }
  }
}
</script>

<style scoped>
.data-pagination {
  float: right;
  margin-top: 20px;
}
</style>

// react-cancelToken/src/views/MessageManage.jsx
import React, { useState, useEffect } from 'react';
import { Table, message } from 'antd';
import get from 'lodash/get';
import axios from 'axios';
import withCancelRequest from '../hoc/withCancelRequest';

function MessageManageponent (props) {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const { cancelToken } = props;
  const columns = [
    {
      title: '索引',
      dataIndex: 'index',
      align: 'center'
    },
    {
      title: '名称',
      dataIndex: 'name',
      align: 'center'
    },
    {
      title: '年龄',
      dataIndex: 'age',
      align: 'center'
    },
    {
      title: '财产',
      dataIndex: 'money',
      align: 'center',
      render: text => `${text}元`
    }
  ];

  const getMessageData = () => {
    setLoading(true);
    axios.get('http://localhost:7000/message', { cancelToken }).then(res => {
      if (res.data && res.data.success) {
        const data = get(res, 'data.message', []);
        setData(data);
        setLoading(false);
      }
    }).catch(err => {
      const errMessage = err.message || '获取数据失败';
      console.log(errMessage);
      message.error(errMessage);
    });
  };

  useEffect(getMessageData, []);

  return (
    <Table
      bordered
      rowKey="index"
      columns={columns}
      dataSource={data}
      loading={loading}
      locale={{ emptyText: '暂无数据' }}>
    </Table>);
}

export default withCancelRequest(MessageManageponent, '信息管理页面');
